name: donut-chart

alias:
  - doughnut chart

plotdb: 1042

category:
  - proportion

description:
  en: N/A
  zh: |
    ?[pie-chart]的變形。同樣地，依資料比例將一個圓切分成不同角度的圓餅來表現資料的一種圖表，不過這個圓是空心的，所以我們也可以說是切割了一個「環」、或是「甜甜圈」，因此叫做?[donut-chart]。

    相較於?[pie-chart]使用完整的圓，?[donut-chart]省去了圓中心的部份，而僅以圓周的比例來表現資料，不僅減少了墨水的使用量，也留下了更多空間可以提供額外的資訊。不過，這樣做使得原先?[pie-chart]以角度比較資料的方式變成以弧長來比較資料。參考 Tableau Research 的研究「[Arcs, Angles, or Areas: Individual Data Encodings in Pie and Donut Charts](https://research.tableau.com/paper/arcs-angles-or-areas-individual-data-encodings-pie-and-donut-charts)」，兩者並沒有相當明顯的判讀差異，因此通常也是在設計的考量下選擇使用其中一者。

    ?[pie-chart]會碰到的問題，?[donut-chart]都會發生，例如跨圖表比較的效率低落、不適合同時呈現過多資等等，然而?[donut-chart]仍大量被運用在表現進度、完成度等需要強調整體的時機。

commonPractice:
  en: N/A
  zh: |
    * 表現整體與部份的比例
    * 當談到「比例」、「市佔」、「佔了..成」等與整體相比的概念時，可以嘗試使用?[donut-chart]來呈現。

pros:
  en: N/A
  zh: |
    * 清楚的表現比例，尤其在小資料集
    * 呈現 25% 、50% 等直角比例效果尤佳
    * 比起?[pie-chart]有較高的資料墨水比。

cons:
  en: N/A
  zh: |
    * 不適用於順序式資料或大量資料。
    * 不適合跨圓餅圖進行比較。
    * 資料過於相近或比例懸殊時效率或較差。

guideline:
  en: N/A
  zh: |
    * 若顯示比例，其總和需為 100%
    * 建議從 12 點鐘方向開始順時針方向排序
    * 2 ~ 7 筆資料為佳。
    * 避免用於跨圖表比較。

alternative:
  en: N/A
  zh: |
    * 通常可直接改用?[pie-chart]。
    * 需要跨圖表比較時，可改用 ?[stacked-bar-chart] 或是 ?[slopegraph]
    * 資料量過多時，可將比例較小的部份合併顯示。
    * 資料量過多時，可將部份圓餅合併至另一張長條圖顯示。
    * 只有兩筆資料卻需要跨圖表比較時，可使用 ?[pie-bubble]

dimension:
  - [angle, ratio, required]

visualEncoding:
  - angle

variant:
  - lollipop-with-pie
  - pie-chart
  - sun-burst-diagram
  - curved-bar-chart

keyword:
  en: N/A
  zh:
    - 比例
    - 比值
    - 部份
