name: lollipop-chart

plotdb: 1062

category:
  - comparison

description:
  en: N/A
  zh: |
    本質上與?[bar-chart]相同，利用線段長度呈現資料的一種圖表。通常線段遠比一般?[bar-chart]中的長條還要細上很多，而在線段的末端會加上一個圓點來強調數值的大小。

    由於與?[bar-chart]差異不大，通常使用?[lollipop-chart]的考量都僅僅是為了美觀；不過，密集的長條有時會產生摩爾紋 ( Moire Pattern ) 影響閱讀，此時使用以細線表示長度的?[lollipop-chart]可以大大減輕這個問題。此外，繪製?[lollipop-chart]使用的墨水量一般也比?[bar-chart]少上許多。

    有時?[lollipop-chart]亦指將末端的圓點以?[pie-chart]或?[donut-chart]取代的形式，是為?[bar-chart]與?[pie-chart]的組合型「?[lollipop-with-pie]」。這時不只可以表現數值的大小，也可以用來比較長條中各數值的比例。不過，通常效果不會比?[stacked-bar-chart]好，除非在各個長條中的資料組數只有兩組。

commonPractice:
  en: N/A
  zh: |
    * 欲比較資料，又(為了設計)需要有別於?[bar-chart]的圖表時。
    * 以?[bar-chart]呈現資料而產生了摩爾效應時，可嘗試改用?[lollipop-chart]

pros:
  en: N/A
  zh: |
    * 比起?[bar-chart]有較高的資料墨水比。
    * 可搭配?[pie-chart]、?[bubble-chart]而有更多的變化。

cons:
  en: N/A
  zh: |
    * 相較於?[bar-chart]，資料判讀的效率並沒有較好。
    * 不像?[bar-chart]，?[lollipop-chart]不適合堆疊使用。

guideline:
  en: N/A
  zh: |
    * 圖表的座標原點需由零開始
    * 數據排序後呈現為佳
    * 比起有序資料，更適合運用在無序資料上
    * 適當使用格線與軸線刻度可增加資料判讀的正確性

alternative:
  en: N/A
  zh: |
    * 通常可直接改用?[bar-chart]。

dimension:
  - [x-coord, any, required]
  - [y-coord, ratio, required]

visualEncoding:
  - aligned-length

variant:
  - lollipop-with-pie
  - bar-chart
  - dot-chart

keyword:
  en: N/A
  zh: N/A
