name: pie-chart

alias:
  - circle chart

plotdb: 1040

description:
  en: N/A
  zh: |
    依資料比例將一個完整的圓切分成不同角度的圓餅來表現資料的一種圖表。由於圓與圓餅分別暗示了整體與部份，因此圓餅圖通常用以表現資料個別與整體之間的比例，並不適合用來表現資料的絕對數值。

    實務上，圓餅的角度變化較不容易被觀察到 ( 尤其是與長條圖相比 ) ，所以比較不建議用來表現資料間的變化，也不適合做各筆資料間的比較。即使想要比較兩個圓餅的數據，通常也會使用判讀上更為容易的長條圖。

    此外，由於繞圓一圈也只有 360 度，尤其是在圓的半徑並不長的情況下，圓餅圖並沒有辦法放入太多筆資料，通常以七組數據為上限。由於容易被誤用，圓餅圖常被建議不要使用，使用時應特別注意。

pros:
  en: N/A
  zh: |
    * 清楚的表現比例，尤其在小資料集
    * 呈現 25% 、50% 等直角比例效果尤佳

cons:
  en: N/A
  zh: |
    * 不適用於順序式資料或大量資料。
    * 不適合跨圓餅圖進行比較。
    * 資料過於相近或比例懸殊時效率或較差。
    * 最常遭誤用的一種圖表。

guideline:
  en: N/A
  zh: |
    * 避免使用 ?[pie-chart-3d]
    * 若顯示比例，其總和需為 100%
    * 建議從 12 點鐘方向開始順時針方向排序
    * 2 ~ 7 筆資料為佳。
    * 避免用於跨圖表比較。

classicExample: |
  * Steve Jobs’s "U.S. SmartPhone Marketshare" pie chart.

mediaUsage:
  - author: Fox Chicago
    title: 2012 Presidential Run
    media: Fox Chicago
    year: 2014
    link: http://peltiertech.com/use-bar-charts-not-pies/

category:
  - proportion

dimension:
  - [angle, ratio, required]

visualEncoding:
  - angle

commonPractice:
  en: N/A
  zh: |
    * 表現整體與部份的比例
    * 當談到「比例」、「市佔」、「佔了..成」等與整體相比的概念時，可以嘗試使用?[pie-chart]來呈現。

keyword:
  en: N/A
  zh:
    - 比例
    - 比值
    - 部份

alternative:
  en: N/A
  zh: |
    * 通常可直接改用?[donut-chart]。
    * 需要跨圖表比較時，可改用 ?[stacked-bar-chart] 或是 ?[slopegraph]
    * 資料量過多時，可將比例較小的部份合併顯示。
    * 資料量過多時，可將部份圓餅合併至另一張長條圖顯示。
    * 只有兩筆資料卻需要跨圖表比較時，可使用 ?[pie-bubble]

variant:
  - donut-chart
  - polar-chart
  - sun-burst-diagram
  - pie-chart-3d
  - pie-bubble

bannerConfig:
  [{
    margin: 10, background: "#eee", gridBackground: "none",
    padding: 12,
    palette: {colors: [{hex: "#444"},{hex: "#666"},{hex: "#999"}]},
    legendShow: false,
    fill: "rgba(100%,63%,40%,0.7)",
    fontSize: 11,
    fontFamily: "arial",
    gridStrokeWidth: 1,
    gridDashArray: "1 0",
    gridStroke: "#ddd",
    gridFrameStrokeWidth: 0,
    textFill: "#666",
    sort: "Descending",
    xAxisTickSizeInner: 0,
    xAxisTickSizeOuter: 0,
    yAxisHandleOverlap: "none",
    yAxisShowDomain: true,
    yAxisStroke: "#aaa",
    labelShow: true
  },{
    margin: 10, background: "#eaeff5", gridBackground: "#eaeff5",
    palette: {colors: [{hex: "#fff"},{hex: "#ffd"},{hex: "#fdf"}]},
    fill: "rgba(14%,35%,50%,0.8)",
    padding: 6,
    fontSize: 13,
    fontFamily: "tahoma",
    labelShow: false,
    gridStrokeWidth: 0,
    gridDashArray: "1 0",
    gridStroke: "rgba(0,0,0,0)",
    gridFrameStrokeWidth: 0,
    textFill: "#554",
    sort: "Ascending",
    xAxisTickSizeInner: 4
  },{
    margin: 10, background: "#f9f9f9", gridBackground: "#f9f9f9",
    palette: {colors: [{hex: "#e96"},{hex: "#ae5"},{hex: "#48d"},{hex: "#999"}]},
    padding: 2,
    legendShow: true,
    fontFamily: "lato",
    fill: "rgba(25%,25%,25%,0.9)",
    fontSize: 12,
    textFill: "#444",
    sort: "None",
    xAxisTickSizeInner: 4,
    yAxisTickSizeOuter: 4,
    gridDashArray: "2 2",
    gridStrokeWidth: 1,
    gridStroke: "#999",
    xAxisStroke: "#999"
  }]
