name: bubble-chart
plotdb: 993

description:
  en: TBD
  zh: |
    以圓面積對應到資料大小、用平面上的多個圓表現資料的一種圖表。圓的位置沒有一定的規則，可以單純地隨意散布、或是以螺旋狀的方式依面積大小排列順序，也可以如 ?[scatter-plot] 般以兩個額外的維度來決定；因此泡泡圖常被視為是 ?[scatter-plot] 的一種變形。

    除了面積與座標外，圓的邊框、填色都可以用來呈現資訊，甚至可以用 ?[pie-chart] 來取代所有的泡泡 ( 即為 ?[pie-bubble] )，或者搭配動畫來表現時序資訊 ( 比方說 [Gapminder](https://www.gapminder.org/) 與 [Hans Rosling 於 TED 中著名的演講](https://www.ted.com/speakers/hans_rosling) 中所用到的圖表 )。位置也可以搭配顏色或額外的圓來為資料分群，?[circular-treemap] 即是一個類似的例子。

    泡泡圖也常疊合至地圖上搭配地理空間表現資訊，比方說統計地圖中的 ?[dorling-cartogram] 即為一例，亦或者配合動畫表現事件與經緯度的 [地理事件視覺化樣版](http://0media.tw/t/geoevent)。除了極富變化外，能表現的資訊維度也多，可說是個很強大、實用的圖表類型。

    泡泡圖運用面積的呈現形式與彈性的排版使得它能夠妥善的運用有限的表現空間，這是長條圖所無法辦到的，然而要注意的是，利用面積表現資料雖然可以很快的讓我們看出大小，卻不適合用來做精確比較或計算比例，尤其是在數值大多相近之時效率更是低落。

    此外，泡泡圖使用上一個常見問題是誤把資料對應到圓的半徑；由於面積是半徑的平方，此時肉眼感受到的數據將會遭到次方倍的扭曲，因此在做圖時需要格外注意。


category:
  - correlation
  - comparison
  - geography
  - distribution

commonPractice:
  en: N/A
  zh: |
    * 常用於處理 3 、4 維以上的資料
    * 數據量大時，可試著用泡泡圖更有效率的運用空間。
    * 僅需對整體資料概觀性的理解，也可嘗試使用泡泡圖。

guideline:
  en: N/A
  zh: |
    * 上色時，避免過於混亂的色調。
    * 務必以面積代表資料。描繪圓形時，半徑應代入資料的平方根。
    * 避免使用圓形以外的形狀，因為圓以外的形狀讓面積計算與比較更加困難。
    * 通常用來比較適合「相加」的資料。溫度、年齡等數據較不適合。

alternative:
  en: N/A
  zh: |
    * 資料變化範圍不大時，應考慮使用 ?[bar-chart] 或 ?[line-chart] 替代。
    * 欲表現數據?[proportion]時，可考慮使用 ?[pie-bubble]。
    * 欲呈現?[hierarchy]關係時，可考慮使用 ?[circular-treemap]
    * 欲呈現空間 / 地理資訊時，可搭配地圖定位，如 ?[bubble-map] 或 ?[dorling-cartogram]。
    * 欲呈現時間資訊時，可利用 ?[animated-scatter-plot]。

dimension:
  - [area, ratio, required]
  - [color, any, optional]
  - [x coord, ratio, optional]
  - [y coord, ratio, optional]

visualEncoding:
  - area
  - color
  - position

variant:
  - pie bubble
  - circular treemap
  - dorling cartogram
  - bubble map

classicExample: |
  * "[Snake Oil Supplements?](http://www.informationisbeautiful.net/visualizations/snake-oil-supplements/)", Information is Beautiful. 

mediaUsage:
  - author: Shan Carter
    title: "Four Ways to Slice Obama's 2013 Budget Proposal"
    media: New York Times
    year: 2012
    link: http://www.nytimes.com/interactive/2012/02/13/us/politics/2013-budget-proposal-graphic.html?_r=0

pros:
  en: N/A
  zh: |
    * 讓讀者快速、粗略地了解數據之間的比較。
    * 適合呈現大量數據。


cons:
  en: TBD
  zh: |
    * 較不易看出資料間的正確比例。
    * 不適合有序性的資料。
