name:
  en: Heatmap
  zh: 熱圖

alias:
  - heat map

plotdb: 1009

category:
  - pattern

dimension:
  - [x, required, any]
  - [y, required, any]
  - [color, required, numeral]

visualEncoding:
  - color

variant:
  - choropleth
  - cohort chart

classicExample:
  en: |
    * Precipitation Map
  zh: |
    * 降雨量圖

mediaUsage:
  - N/A

description:
  en: TBD
  zh: |
    以色階表現資料的一種圖表，常以方塊陣列的形式應用在數值矩陣呈現上，但不限於特定的形狀與排列方式。除了矩陣，另一種常見的應用為網頁行為分析，在這種情境下，熱度圖依網頁不同區域的點擊率高低來描繪色階。應用在地圖上也相當常見，比方說雨量、空氣污染、房產交易熱度等等。能有效率的呈現數據並做概略性的分析，但不容易做資料的精確對比。

pros:
  en: TBD
  zh: |
    可快速取得大範圍資料的重點

cons:
  en: TBD
  zh: |
    資料量不足時較不具意義

commonPractice:
  en: TBD
  zh: TBD

guideline:
  en: TBD
  zh: TBD
