name: histogram
plotdb: 2007

description:
  en: TBD
  zh: |
    一種特化的長條圖，於 1895 年英國統計學家 Karl Pearson 所發明，專門用以表現頻率與分布的概念。並非直接描繪資料集為圖表，而是將資料依照給定的分組計數過後 ( 例如，將總人口切分成 0 ~ 15 歲、 16 ~ 65 歲、 65 以上 三群) ，再將分組的數量表現於長條的長度上。由於資料分組通常都是連續數值，長條間通常都是相連而不留白，這點可用來分辨 ?[column-chart] 與 ?[histogram] 。

    雖然只是一種特化的長條圖，但?[histogram]其實相當實用；攝影上常將相片中的像素依亮度做統計，用來檢視相片是否過曝或曝光不足，而?[population-pyramid]事實上也可以說是一種特製的?[histogram]。

    ?[histogram]亦為品管七大手法之一。

category:
  - distribution

commonPractice:
  en: N/A
  zh: |
    * 當欲表達的概念有談到「分布」、「頻率」、「次數」等關鍵字時，便是嘗試?[histogram]的好時機。
    * 常用在照片分析，用以了解照片的亮度平衡。
    * 任何數列都可以利用範圍分組的方式製出?[histogram]。

guideline:
  en: N/A
  zh: |
    * 長條間不留空白。
    * 一般會用同樣的顏色為所有長條上色，但可以用顏色強調特定區間。


alternative:
  en: N/A
  zh: |
    * 欲呈現兩個維度的資料分布情形時，可用?[scatter-plot]或是立體直方圖。
    * 在空間侷限的情形下，也可以使用?[heatmap]呈現分布。

dimension:
  - [x coord, ratio, required]
  - [y coord, ratio, required]

visualEncoding:
  - aligned length

variant:
  - bar-chart

pros:
  en: N/A
  zh: |
    * 即使大量資料也能很容易的用?[histogram]來表現。
    * 相當適合表現分布。

cons:
  en: N/A
  zh: |
    * 區間分組有時不易拿捏，過大或過小都可能會造成資料的錯誤解讀。
    *
