name: pie-chart-3d

alias:
  - pie chart that sucks

plotdb: 1040

description:
  en: N/A
  zh: |
    圓餅圖的一種變形。與圓餅圖相同的是仍然使用楔形的尖角角度來表現資料，但卻將整個圓想像為一個圓柱來切割；為了表現圓柱的概念，通常會以立體繪圖的形式來表現，因此稱為立體圓餅圖。

    由於立體化，產生了立體圖表常常會有的問題，比方說透視造成的資料扭曲、圓柱側面的額外面積影響了整體資料比例的判讀等等，然而為了設計或視覺效果的考量，使用立體圓餅圖的情況並不少見，甚至許多套裝軟體與線上工具也都有提供產生立體圓餅圖的功能。

    立體圓餅圖的這些缺點使得他成為了最不受歡迎的圖表之一，一般學習過資料視覺化的圖表使用者通常都會避開這類的爭議圖表不要使用。

pros:
  en: N/A
  zh: |
    * 活潑、生動、搭配設計可讓整體內容更吸引人
    * 很容易進行資料操弄，廣受媒體操弄者喜愛

cons:
  en: N/A
  zh: |
    * 扭曲資料並影響判讀。
    * 使用將冒著影響專業度的風險。
    * 容易因此成為負面教材或遭登上 [viz.wtf](http://viz.wtf) 。

guideline:
  en: N/A
  zh: |
    * 避免使用此類圖表
    * 若要使用，則可搭配下列步驟：
        1. 首先將下方拉近、上方推遠
        2. 將對自己有利的部份置於下方
        3. 並妥善運用前進色強化下方圓餅
        4. 將圓餅拉出使用效果尤佳

classicExample: |
  * Steve Jobs’s "U.S. SmartPhone Marketshare" pie chart.

mediaUsage:
  - author: Fox Chicago
    title: 2012 Presidential Run
    media: Fox Chicago
    year: 2014
    link: http://peltiertech.com/use-bar-charts-not-pies/

category:
  - proportion

dimension:
  - [angle, ratio, required]

visualEncoding:
  - angle

commonPractice:
  en: N/A
  zh: |
    * 表現整體與部份的比例
    * 當談到「比例」、「市佔」、「佔了..成」等與整體相比的概念時，可以嘗試使用圓餅圖來呈現。

keyword:
  en: N/A
  zh:
    - 比例
    - 比值
    - 部份

alternative:
  en: N/A
  zh: |
    * 直接改用 ?[pie-chart] ，或 ?[pie-chart] 中建議的其它方案。

variant:
  - donut-chart
  - polar-chart
  - sun-burst-diagram
  - pie-chart
  - pie-bubble

bannerConfig:
  [{
    margin: 10, background: "#eee", gridBackground: "none",
    padding: 12,
    palette: {colors: [{hex: "#444"},{hex: "#666"},{hex: "#999"}]},
    legendShow: false,
    fill: "rgba(100%,63%,40%,0.7)",
    fontSize: 11,
    fontFamily: "arial",
    gridStrokeWidth: 1,
    gridDashArray: "1 0",
    gridStroke: "#ddd",
    gridFrameStrokeWidth: 0,
    textFill: "#666",
    sort: "Descending",
    xAxisTickSizeInner: 0,
    xAxisTickSizeOuter: 0,
    yAxisHandleOverlap: "none",
    yAxisShowDomain: true,
    yAxisStroke: "#aaa",
    labelShow: true
  },{
    margin: 10, background: "#eaeff5", gridBackground: "#eaeff5",
    palette: {colors: [{hex: "#fff"},{hex: "#ffd"},{hex: "#fdf"}]},
    fill: "rgba(14%,35%,50%,0.8)",
    padding: 6,
    fontSize: 13,
    fontFamily: "tahoma",
    labelShow: false,
    gridStrokeWidth: 0,
    gridDashArray: "1 0",
    gridStroke: "rgba(0,0,0,0)",
    gridFrameStrokeWidth: 0,
    textFill: "#554",
    sort: "Ascending",
    xAxisTickSizeInner: 4
  },{
    margin: 10, background: "#f9f9f9", gridBackground: "#f9f9f9",
    palette: {colors: [{hex: "#e96"},{hex: "#ae5"},{hex: "#48d"},{hex: "#999"}]},
    padding: 2,
    legendShow: true,
    fontFamily: "lato",
    fill: "rgba(25%,25%,25%,0.9)",
    fontSize: 12,
    textFill: "#444",
    sort: "None",
    xAxisTickSizeInner: 4,
    yAxisTickSizeOuter: 4,
    gridDashArray: "2 2",
    gridStrokeWidth: 1,
    gridStroke: "#999",
    xAxisStroke: "#999"
  }]
