name: pie-chart-3d

alias:
  - pie chart that sucks

plotdb: 2193

description:
  en: N/A
  zh: |
    圓餅圖的一種變形。與圓餅圖相同的是仍用楔形的角度來表現資料，唯一的不同在於?[pie-chart-3d]將整個圓想像為一個圓柱來切割，類似切蛋糕一般；為了表現圓柱的概念，通常會以立體繪圖的形式來表現，因此稱為?[pie-chart-3d]。

    由於立體化，產生了立體圖表常常會有的問題，比方說透視造成的資料扭曲、圓柱側面的額外面積影響了整體資料比例的判讀等等，然而為了設計或視覺效果的考量，使用立體圓餅圖的情況並不少見，甚至許多套裝軟體與線上工具也都有提供產生?[pie-chart-3d]的功能。

    ?[pie-chart-3d]的這些缺點使得他成為了最不受歡迎的圖表之一，一般學習過資料視覺化的圖表使用者通常都會避開這類的爭議圖表不要使用，一方面避免造成資料的錯誤判讀、另一方面也避免讓讀者覺得作者不夠專業。

    事實上，當圓餅圖只有兩組資料時，適當的旋轉可讓資料扭曲變得比較不這麼嚴重；而在製作?[infographics]時，有時為了視覺效果會使用?[pie-chart-3d]。即便一般都建議避免使用此圖表，若真的有其必要時，還是請自己依照製圖的需求來決定。

pros:
  en: N/A
  zh: |
    * 活潑、生動、搭配設計可讓整體內容更吸引人
    * 很容易進行資料操弄，廣受媒體操弄者喜愛

cons:
  en: N/A
  zh: |
    * 扭曲資料並影響判讀。
    * 使用將冒著影響專業度的風險。
    * 容易因此成為負面教材或遭登上 [viz.wtf](http://viz.wtf) 。

guideline:
  en: N/A
  zh: |
    * 避免使用此類圖表
    * 若要使用，可盡量減少切分數量。
    * 搭配下列步驟可讓資料扭曲最大化：
        1. 首先利用立體透視效果讓下方離讀者較近、上方較遠。
        2. 接著，將對自己有利的部份置於下方。
        3. 此時搭配著將下方圓餅拉出使用效果尤佳。
        3. 妥善運用前進色可以進一步放大下方圓餅。

classicExample: |
  * Steve Jobs’s "U.S. SmartPhone Marketshare" pie chart.

mediaUsage:
  - author: Fox Chicago
    title: 2012 Presidential Run
    media: Fox Chicago
    year: 2014
    link: http://peltiertech.com/use-bar-charts-not-pies/

category:
  - proportion

dimension:
  - [angle, ratio, required]

visualEncoding:
  - angle

commonPractice:
  en: N/A
  zh: |
    * ?[pie-chart-3d]主要是用來呈現比例的圖表，不過通常都會考慮優先使用?[pie-chart]。
    * 通常都為了視覺效果才使用?[pie-chart-3d]。

keyword:
  en: N/A
  zh:
    - 比例
    - 比值
    - 部份

alternative:
  en: N/A
  zh: |
    * 直接改用?[pie-chart]，或?[pie-chart]中建議的其它方案。

variant:
  - donut-chart
  - polar-chart
  - sun-burst-diagram
  - pie-chart
  - pie-bubble

bannerConfig:
  [{
    margin: 10, background: "#eee", gridBackground: "none",
    padding: 12,
    palette: {colors: [{hex: "#444"},{hex: "#666"},{hex: "#999"}]},
    legendShow: false,
    fill: "rgba(100%,63%,40%,0.7)",
    fontSize: 11,
    fontFamily: "arial",
    gridStrokeWidth: 1,
    gridDashArray: "1 0",
    gridStroke: "#ddd",
    gridFrameStrokeWidth: 0,
    textFill: "#666",
    sort: "Descending",
    xAxisTickSizeInner: 0,
    xAxisTickSizeOuter: 0,
    yAxisHandleOverlap: "none",
    yAxisShowDomain: true,
    yAxisStroke: "#aaa",
    labelShow: true,
    stroke: "#fff",
    legendInline: false
  },{
    xAxisTickSizeInner: 4,
    stroke: "#666",
  },{
    margin: 10, background: "#f9f9f9", gridBackground: "#f9f9f9",
    palette: {colors: [{hex: "#e96"},{hex: "#ae5"},{hex: "#48d"},{hex: "#999"}]},
    padding: 2,
    legendShow: true,
    fontFamily: "lato",
    fill: "rgba(25%,25%,25%,0.9)",
    fontSize: 12,
    textFill: "#444",
    sort: "None",
    xAxisTickSizeInner: 4,
    yAxisTickSizeOuter: 4,
    gridDashArray: "2 2",
    gridStrokeWidth: 1,
    gridStroke: "#999",
    xAxisStroke: "#999"
  }]
