name:
  en: Treemap
  zh: 樹狀區塊圖

alias:

plotdb: 1006

category:
  - hierarchy

dimension:
  - [area, required, numeral]
  - [group, optional, nominal]

visualEncoding:
  - area
  - color

variant:
  - voronoi treemap
  - circular treemap
  - jigsaw treemap
  - convex treemap

classicExample:
  - N/A

mediaUsage:
  - N/A

description:
  en: TBD
  zh: |
    1991 年由 BenShneiderman 發明、使用層層相疊的矩形表示階層式資料的視覺化手法。樹狀區塊圖通常用矩形的面積來類比數據大小，並以邊界或色調表現資料分組，再加上其階層的本值，因此相當適合在表現階層式資料的同時仍提供資料間對比的線索。它也有效率地運用了所有的顯示空間。資料量大時可能會降低可讀性，適當的著色與運用互動機制可以改善這個問題。

pros:
  en: TBD
  zh: |
    清楚表現階層式資料之間數據的對比

cons:
  en: TBD
  zh: |
    少量、非階層式等的資料使用長條圖等方式會更適合

commonPractice:
  en: TBD
  zh: TBD

guideline:
  en: TBD
  zh: TBD
